### ISSUE TITLE
Limitations of the Matcher Trait with Proxy reference type

### ISSUE THREAD

**Issue by bjacotg** [google/googletest-rust#323]
See [this playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=673a75390be29b01b670d98cbe0b9498) for a minimal example.

While implementing matchers for the [Rust protobuf library](https://github.com/protocolbuffers/protobuf/tree/main/rust), I stumbled on an issue with the lifetime requirement of the Matcher trait. The lifetime issue still did not click right in my head, so forgive me if what I say is not exactly what is happening. But, as far as I currently understand it, the `Matcher` trait accepts `&ActualT` with any lifetime even though `ActualT` may be bounded, which makes the `impl Matcher` not able to access most functions of `ActualT`.

I see a few options to solve this issue:
* Add a lifetime requirement on `&ActualT` to have a lifetime smaller than `ActualT`.
  * Not sure if this will work. In my current set up with the protobuf, I managed to get it work, but of course all the other matchers do not work and will need to be updated.
* Accept `ActualT` and not `&ActualT` in matcher, and constraint `ActualT` with `Copy`
  * Not sure if this will work either. Same as above, it fixes the current issue, but it may break other use cases.
* Do not support this pattern. Or the library is buggy
  * Potentially, but I couldn't pinpoint where, so I still currently believe that the `Matcher` trait is just not right.

This reminds me of the issue we currently have with `property!()` and string slices as it was also a reference lifetime issue.

I will add more details while debugging further.

Current leads:
- [ ] Adding the lifetime bound on the `Matcher` trait and see where it takes us
- [ ] Constraining on `Copy` and see where it takes us
- [ ] Changing the return lifetime of `get_a_field()` in the example from `'_` to `'a` seems to work, so maybe there is an issue in the library

**Comment by hovinen** [comment]
I fiddled with the playground and got things to compile: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=c9f86ed89ac8cf349a590f089b99b632

I needed to add a lifetime parameter to the `Matcher` trait among other changes. This feels pretty awkward. I'll play around a bit more to see what alternatives there are.

**Comment by bjacotg** [comment]
Nice find. I had a solution but with more lifetime parameters and clunkier.

The real world example was in:
* Attempt at implementing directly: https://github.com/bjacotg/protobuf/pull/4/files
* My first attempt with lifetime: https://github.com/bjacotg/protobuf/pull/3/files
* Your proposal: https://github.com/bjacotg/protobuf/pull/1/files
* The copy proposal: https://github.com/bjacotg/protobuf/pull/2/files

**Comment by hovinen** [comment]
At the same time, the `ArenaHolder` code looks odd to me:

    impl<'a> ArenaHolder<'a, Strukt> {
        fn get_a_field(&self) -> ArenaHolder<'_, i32> {
            ArenaHolder {
                value: &self.value.a_field,
            }
        }
    }

This is equivalent to

    impl<'a> ArenaHolder<'a, Strukt> {
        fn get_a_field<'b>(&'b self) -> ArenaHolder<'b, i32> {
            ArenaHolder {
                value: &self.value.a_field,
            }
        }
    }

The signature claims that the returned `ArenaHolder` will hold a reference whose lifetime is that of `&self`. But it's actually just taking a reference to a field in `self.value`, which has the lifetime `'a` given by the lifetime parameter. And since it constructs a new `ArenaHolder`, there's no reason for its lifetime to be restricted to that of the `self` reference. So why not do this?

    impl<'a> ArenaHolder<'a, Strukt> {
        fn get_a_field(&self) -> ArenaHolder<'a, i32> {
            ArenaHolder {
                value: &self.value.a_field,
            }
        }
    }

**Comment by hovinen** [comment]
Okay, I understand now. The `as_view` method is explicitly present to reborrow the value with the lifetime of the `ViewProxy` which contains it.

Is there perhaps a way to avoid the reborrow? Can you show how you are building a matcher with the concrete library?

**Comment by hovinen** [comment]
I just ran into the same problem when trying to add a matcher for byte sequences. See #327.

The good news is that the example is much simpler. Perhaps this justifies adding a lifetime parameter to `Matcher`.

**Comment by hovinen** [comment]
I've tried adding a lifetime parameter to `Matcher`.  Unfortunately this leads to more trouble with existing nested matchers. This fixes a specific lifetime as part of the matcher type. Whenever the outer matcher constructs a variable temporarily with which to use the inner matcher, that creates a lifetime which conflicts with the one embedded in the inner matcher's type. So the result does not compile.

See the result on [this playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=971332e7fb53198453be33d0ae9f55e6). Here I try the approach out with the `displays_as` and `is_utf8_string` matchers.

I have also tried switching the `Matcher` methods to be pass-by-value rather than pass-by-reference. The problem here is that implementations of `Matcher` must then set `ActualT` to be a _reference_ in most cases. That reference must then have a named lifetime, which must come from somewhere. The only place from which it can come is again a lifetime parameter on the `impl` block, so one is back to the problem described above. What's more, the lifetime parameter is then no longer constrained by anything (associated types don't count), so the compiler complains.

**Comment by bjacotg** [comment]
I managed to get some success on the displays_as with an existential lifetime (which should work here, since `String` is concrete). See [this playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=5ec8bed4cff8f6e667ba13022c3e42d2). 

However, this is probably tricky to generalize to fully generic matchers.

**Comment by hovinen** [comment]
Yeah, I tried using the `where for<'b>` method, but then couldn't use the matcher:

```
error: implementation of `matcher::Matcher` is not general enough
   --> googletest/src/matchers/char_count_matcher.rs:163:17
    |
163 |               err(displays_as(contains_substring(indoc!(
    |  _________________^
164 | |                 r#"
165 | |                 Value of: "äöüß"
166 | |                 Expected: has character count, which is equal to 3
167 | |                 Actual: "äöüß",
168 | |                   which has character count 4, which isn't equal to 3"#
169 | |             ))))
    | |_______________^ implementation of `matcher::Matcher` is not general enough
    |
    = note: `matcher::Matcher<'0>` would have to be implemented for the type `StrMatcher<'_, String, &str>`, for any lifetime `'0`...
    = note: ...but `matcher::Matcher<'1>` is actually implemented for the type `StrMatcher<'1, String, &str>`, for some specific lifetime `'1`

```

![image](https://github.com/google/googletest-rust/assets/597123/4af90304-774c-4515-806c-b875500cb17f)

(This requires a lot of the library, so it's hard to put in a playground unfortunately.)

**Comment by bjacotg** [comment]
Hmmm, yeah, that would need a bit of extra work. 

I will try to create a branch with only a few matcher implementations so it is easy to iterate over different trait definitions. I will add also the playground example of the `ArenaHolder`.

This will make it easier to share attempts of new trait definition and avoid the limitation of the playground.

**Comment by hovinen** [comment]
I had tried your first proposal but didn't get far.

I think your second proposal has the right idea. It _almost_ compiles; see [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=3047aa6b971ed43169be7b3b9151d3da). The error I get is that putting the reference on an associated type is not considered to constrain the lifetime parameter. This is a [known issue](https://github.com/rust-lang/rust/issues/49601) in Rust.

If I replace the associated type with a type parameter, it does compile. See [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=f7466b7f4579dcbbb5c79bb3b2512925). Of course, we had a good reason to switch to using an associated type, so I don't think that's the answer. Rather it would be great to fix the underlying issue in rustc.

**Comment by hovinen** [comment]
After lots of playing around with lifetimes, I did find a set of incantations which works in the case I linked above. See [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=abaa6e035da74847e1ccc8854e380e4c).

This is based on your second proposal, but has the twist that the `ActualT` used in the inner matcher is changed from `&str` to `str`. That requires adding `?Sized` bounds everywhere, but that's actually fine, since `ActualT` is never passed by value.

Let me see whether this can be generalised.

**Comment by bjacotg** [comment]
My current last attempt is to move back to generic parameters with this new matcher interface:
```
trait Matcher<ActualT> {
  fn matches<'a>(&self, actual: &'a ActualT) -> MatcherResult where ActualT: 'a;
}
```

I was expecting that this will cost us the support for `Matcher::and(...)` but in [this PR](https://github.com/bjacotg/minimal-googletest-rust/pull/1), `Matcher::and(...)` still seems to work.

I will work more on it, after a few PR reviews.

**Comment by bjacotg** [comment]
(referencing conversation in #336 ) `Matcher::and(...)` is working with generic parameters since I kept the `PhantomData` field necessary for the associated type. This looked quite promising at first since we could keep both the support for `Matcher::and(...)` and the proto matchers by sprinkling seemingly unnecessary `PhantomData` fields.


However, you can't have your cake and eat it. Consider [this test](https://github.com/bjacotg/minimal-googletest-rust/blob/pure_generic_parameter/googletest/tests/arena_test.rs).

The compiler rejects this code with:

```
error: implementation of `googletest::matcher::Matcher` is not general enough
  --> googletest/tests/arena_test.rs:68:26
   |
68 |     verify_that!(holder, has_a_field(eq(33)))?;
   |                          ^^^^^^^^^^^^^^^^^^^ implementation of `googletest::matcher::Matcher` is not general enough
   |
   = note: `EqMatcher<ArenaHolder<'2, i32>, i32>` must implement `googletest::matcher::Matcher<ArenaHolder<'1, i32>>`, for any lifetime `'1`...
   = note: ...but it actually implements `googletest::matcher::Matcher<ArenaHolder<'2, i32>>`, for some specific lifetime `'2`
```


With the `PhanthomData` field, `EqMatcher` is forced to a fixed lifetime and cannot meet the bound: `for<'b> Matcher<ArenaHolder<'b, i32>>`.

Moreover, matchers cannot be returned by `impl Matcher<T>`, as it would run in the same issue.

Hence, continuing with this approach will require to:
* Remove the PhantomData fields in matchers
* Remove the support for `Matcher::and(...)`
* Make all matcher struct public and return by their structure


I am still not convince this approach is the best (whether it would work).

**Comment by bjacotg** [comment]
The approach described above does work, but sacrifices `Matcher::and(...)`. However, I investigated this a little further and 

I tried to look back at the `Matcher::and(...)` issues in the playground.

The simplest reproducible examples are:
* [*With PhantomData*](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=f396be1d1880b7b7db9f2d22e9e80e29)
* [*Without PhantomData*](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=a45979be09207f672bc67818bdd0b7a1)


Of course, removing the explicit `ActualT` in *Without PhantomData* is rejected by the compiler. But the log outputs with `Matcher::<str>` is interesting:

```
Calling Matcher::and with type *str*
Calling Conjunction::matches with type *alloc::string::String*
Calling MyMatcher::matcher with type *String*
Calling MyMatcher::matcher with type *String*
```

Somehow, the type checker is only confused on picking which `Matcher::<_>::and(..., ...)` but can decide on the rest (and go with `String`s). In the *With PhantomData*, this problem does not come up. Since the type checker decides that `MyMatcher` should be a `Matcher<String>` then it is forced into `Matcher::<String>::and(...)`.

But, the type checker shouldn't need to decide since `Matcher::<str>::and(...)` and `Matcher::<String>::and(...)` are the same functions, and does not depend on `str` or `String`. This can be achieved with a non-generic trait extensions like in [this playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=0be5253980769c1bc257c3ba6b5c0920). This solution has still some issues, but could be refined further.

Another approach is to rely on impl trait in return to tip the type checker in the right direction. But I did not find a working solution.

**Comment by bjacotg** [comment]
I have finished one last experimentation and it seems that we have the following options:

#336 which migrate back to generic parameter, but trade automatically injecting `Matcher::and` and `Matcher::or` on all `Matcher` for this.

The trade can be handled by:
* Removing `Matcher::and` and `Matcher::or` as this feature is supported by `all!` and `any!`
*  Injecting a non-generic trait extension on all types (like in [this playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=0be5253980769c1bc257c3ba6b5c0920))
* Requiring a non-generic trait extension be added to each `Matcher` implementation (like in [this playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=b00ada29a8dd27db55898a629e07b49c))

#353 which keeps associated types but let constrain the lifetime of `&Self::ActualT`


Both solutions make heavy use of HRTB which require to make the return types explicit (not through `impl Matcher`). This may be tricky for `Matcher` which type erase their inner matchers (like `all!`, `any!`, `unordered_elements_are!`, etc..)

**Comment by hovinen** [comment]
I've given this problem a bit more thought and looked more closely at the code in the protobuf library.

The basic problem occurs when one needs an inner matcher whose `ActualT` includes a lifetime. One must name the lifetime somehow. Normally one does this by:

 * adding a lifetime parameter to the struct, or
 * using the `for <'a>` construct to require that the inner matcher apply to _all_ lifetimes.

But that lifetime is defined by the function `Matcher::matches`. So the first option of binding it to the struct is going to cause problems: at the very least, one must bring it into a relation with lifetime of the actual value passed to `matches`. This requires adding a bound to the trait itself, which means going down a rabbit hole.

The second option doesn't work because the type of the inner matcher is already fixed. So the lifetime of `ActualT` is fixed (even if unknown) and one can't declare that the matcher work with any lifetime.

In the case of `ViewProxy` from the protobuf library, that's basically just a kind of smart reference. It also needs a lifetime, and if one is going to write a matcher which matches against it, one needs to name that lifetime.

The idea of removing the reference to the actual value (and therefore requiring that that actual value be `Copy`) is an attempt to address the problem by removing one of the two lifetimes which need to be brought into relation, namely, that of the parameter `actual`. I have concerns about the effect of this solution on the rest of the library, as I wrote in my comment on PR #367. Namely, I still see a lot of places in that PR which involve adding reference operators in what look like completely arbitrary places. For example:

```
- verify_that!(vec![1, 2, 3], elements_are![eq(1), anything(), gt(0).and(lt(123))])
+ verify_that!(vec![1, 2, 3], elements_are![eq(&1), anything(), gt(&0).and(lt(&123))])
```

This will make the library much harder to understand and reason about.

I wonder whether there is another solution which is somewhere between the current state and #367. Namely, perhaps `actual` could accept general references which include `ViewProxy`, leaving the rest of the use of the library unchanged. I'll try some things out and see whether something can be done.

I've found a solution for the problem with `is_utf8_string` which, I think, should be okay for users. It relies on ensuring that `ActualT` does not include any references. I've sent PR #368 with this change.

**Comment by hovinen** [comment]
I've done some more experimenting and may have found a solution. See [this commit](https://github.com/google/googletest-rust/commit/1e0b74ea6f232ed3cb90299ab66802ca053c53ff). It works on the example of the playground to which you linked, with the addition that the `ViewProxy` struct (what you called `ArenaHolder`) implements `Deref` to the type it is proxying.

That said, I'm wondering what kind of API you envision for matching against protos. Do you envision something like 'matches_pattern!`, based on a kind of property matcher?

I'm not sure that the any of the approaches discussed here can work for that. Namely, the property matcher is based on an extractor closure which would in this case return a `ViewProxy` whose lifetime is limited to that of the parameter passed to it. But that parameter does not live longer than the call to the closure, so it cannot return such a `ViewProxy`. In the above commit, I added a test `googletest/tests/arena_test.rs` which illustrates the problem.

At the same time, it seems that an approach requiring the creation of a matcher for each field in the proto, as with `has_a_field` in  your playground, will not really scale.

I'd suggest first clarifying exactly what kind of API you want to see for matching protos, then solving directly for that desired API.
